# This is a basic workflow to help you get started with Actions

name: Healthy_Sign_Action

# Controls when the workflow will run
on:
  # Script Run Time
  schedule:
    - cron: 30 06 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          
      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip isntall -r requirements.txt
      
      # Runs a single command using the runners shell
      - name: Run Script
        env:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        run: python healthy.py
